DROP TABLE IF EXISTS STAR_WARS_PLANETS;

CREATE TABLE STAR_WARS_PLANETS (
	ID                  INT PRIMARY KEY auto_increment,
	PLANET_NAME         VARCHAR(30),
	POSTING_OPERATOR_ID VARCHAR(8),
	POSTING_TIMESTAMP   TIMESTAMP(6)
);